Repository yoru-ui/yoru-ui, pull requests merged in 2022-11, with the labels that each got.

#24 refactor useResolvedThemes and remove unnecessary hook theme
  packages/button/src/button.tsx
  packages/button/stories/button.stories.tsx
  packages/themes/src/components/button.ts
  packages/themes/src/hook/index.tsx
  packages/themes/src/types/index.ts
  packages/themes/src/utils/styled-config.ts
Labels: enhancement

#29 Feature/input, mode utility, types.
  packages/core/src/pseudo.ts
  packages/input/ReadMe.md
  packages/input/package.json
  packages/input/src/index.tsx
  packages/input/src/input.tsx
  packages/input/stories/input.stories.tsx
  packages/input/tests/input.test.tsx
  packages/themes/src/components/index.ts
  packages/themes/src/components/input.ts
  packages/themes/src/hook/index.tsx
  packages/themes/src/theme.tsx
  packages/themes/src/types/index.ts
  packages/themes/src/utils/theme-utils.ts
  packages/utils/src/function.ts
Labels: enhancement, feature

#31 Feature/switch
  packages/core/src/configs/pseudo.ts
  packages/core/src/css.ts
  packages/switch/ReadMe.md
  packages/switch/package.json
  packages/switch/src/index.tsx
  packages/switch/src/switch.tsx
  packages/switch/stories/switch.stories.tsx
  packages/switch/tests/switch.test.tsx
  packages/themes/src/components/index.ts
  packages/themes/src/components/switch.ts
  packages/themes/src/hook/index.tsx
Labels: feature

#33 Feature/checkbox
  packages/checkbox/ReadMe.md
  packages/checkbox/package.json
  packages/checkbox/src/checkbox.tsx
  packages/checkbox/src/index.tsx
  packages/checkbox/stories/checkbox.stories.tsx
  packages/checkbox/tests/checkbox.test.tsx
  packages/core/src/configs/pseudo.ts
  packages/core/src/css.ts
  packages/core/src/utils/index.ts
  packages/themes/src/components/checkbox.ts
  packages/themes/src/components/index.ts
  packages/themes/src/components/switch.ts
  packages/themes/src/hook/index.tsx
  packages/utils/src/object.ts
Labels: enhancement, feature

#37 Strongly typed resolved themes
  packages/button/src/button.tsx
  packages/checkbox/src/checkbox.tsx
  packages/themes/src/components/button.ts
  packages/themes/src/components/checkbox.ts
  packages/themes/src/components/index.ts
  packages/themes/src/components/input.ts
  packages/themes/src/hook/index.tsx
  packages/themes/src/types/index.ts
  packages/themes/src/utils/styled-config.ts
Labels: enhancement, feature

#38 Enhance button component
  .storybook/preview.js
  package.json
  packages/button/src/LoadingIcon.tsx
  packages/button/src/button.interface.ts
  packages/button/src/button.tsx
  packages/button/stories/button.stories.tsx
  packages/button/tests/button.test.tsx
  packages/themes/src/components/button.ts
  packages/themes/src/components/index.ts
  packages/themes/src/foundations/index.ts
  packages/themes/src/hook/index.tsx
  packages/themes/src/index.ts
  packages/themes/src/types/index.ts
Labels: enhancement
