Repository yoru-ui/yoru-ui, pull requests merged in 2022-08, with the labels that each got.

#1 Feature/component generator
  .eslintrc.js
  ReadMe.md
  package.json
  plop-templates/ReadMe.md.hbs
  plop-templates/package.json.hbs
  plop-templates/src/index.tsx.hbs
  plop-templates/src/{{componentName}}.tsx.hbs
  plop-templates/tests/{{componentName}}.test.tsx.hbs
  plopfile.js
Labels: feature

#4 Feat/yoru-system-style
  packages/system/package.json
  packages/system/src/system.ts
Labels: feature

#7 Feat/yoru-pseudo-transformer
  packages/system/src/pseudo.ts
  packages/system/src/system.ts
Labels: feature

#9 Feat/yoru-core
  package.json
  packages/core/index.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/pseudo.ts
  packages/core/src/system.ts
  packages/core/test/core.test.tsx
Labels: enhancement

#12 Feat/global css vars
  .eslintrc.js
  lint-staged.config.js
  packages/core/src/configs/color.ts
  packages/core/src/configs/index.ts
  packages/core/src/create-css-variable.ts
  packages/core/src/css-var.ts
  packages/core/src/css.ts
  packages/core/src/index.ts
  packages/core/src/pseudo.ts
  packages/core/src/system.ts
  packages/core/src/utils/index.ts
  packages/themes/package.json
  packages/themes/src/create-theme-vars.ts
  packages/themes/src/theme.tsx
Labels: enhancement

#15 [feat/custom-theme-config] allow to merge custom theme with base theme
  packages/themes/package.json
  packages/themes/src/theme.tsx
  packages/utils/src/index.ts
  packages/utils/src/object.ts
  packages/utils/src/test/assertion.test.ts
  packages/utils/src/test/function.test.ts
  packages/utils/src/test/object.test.ts
Labels: enhancement, feature

#17 Feat/pseudo css transform
  packages/core/src/configs/color.ts
  packages/core/src/configs/index.ts
  packages/core/src/configs/pseudo.ts
  packages/core/src/create-theme-vars.ts
  packages/core/src/css.ts
  packages/core/src/index.ts
  packages/core/src/pseudo.ts
  packages/core/src/utils/index.ts
  packages/core/test/core.test.tsx
  packages/themes/src/components/button.ts
  packages/themes/src/theme.tsx
Labels: enhancement, feature

#19 Feat/style props
  packages/core/src/configs/index.ts
  packages/core/src/configs/pseudo.ts
  packages/core/src/css.ts
  packages/core/src/styled.ts
  packages/core/src/system.ts
  packages/core/test/core.test.tsx
  packages/themes/src/components/button.ts
  packages/utils/src/object.ts
  packages/utils/src/test/object.test.ts
Labels: enhancement, feature

#21 setup storybook decarator
  .storybook/preview.js
  package.json
Labels: feature
